apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1 # {"$kpt-set":"replicas"}
  template:
    spec:
      containers:
      - name: nfs-client-provisioner
        env:
        - name: PROVISIONER_NAME
          value: cluster.local/nfs-client-provisioner  # {"$kpt-set":"provisioner"}
        - name: NFS_SERVER
          value: nfsserver # {"$kpt-set":"nfs-server"}
        - name: NFS_PATH
          value: /ifs/kubernetes # {"$kpt-set":"nfs-path"}
      volumes:
      - name: nfs-client-root
        nfs:
          path: /ifs/kubernetes # {"$kpt-set":"nfs-path"}
          server: nfsserver # {"$kpt-set":"nfs-server"}
