kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
nameSuffix: "" # {"$kpt-set":"name-suffix"}
namespace: "" # {"$kpt-set":"namespace"}
resources:
- base
patches:
- path: patches/deployment-nfs-client-provisioner.yaml
- path: patches/storageclass-nfs-client.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
