kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- base
patches:
- path: patches/deployment-nfs-client-provisioner.yaml
commonLabels:
  app.kubernetes.io/managed-by: kustomize
