apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    config.kubernetes.io/function: |
      container:
        image: kumorilabs/kpt-fn-remove-role-binding-subject-namespace:0.1
    config.kubernetes.io/local-config: "true"
